name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: cuaesd/aesd-autotest:24-unit-test
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    runs-on: ubuntu-latest
    container: cuaesd/aesd-autotest:24-assignment2
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build writer
        run: make

      - name: Verify writer exists
        run: ls -l finder-app/writer

      - name: Make writer executable
        run: chmod +x finder-app/writer

      - name: Run finder test
        run: |
          cd finder-app
          chmod +x finder-test.sh
          ./finder-test.sh
